version: '3.8'

services:
  # Neo4j Database
  neo4j:
    image: neo4j:5.14
    container_name: neo4j_db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password123
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - app_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  # Backend API
  backend:
    build: ./backend
    container_name: backend_api
    ports:
      - "8000:8000"
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password123
      SECRET_KEY: your-super-secret-key-change-this-in-production
      REDIS_URL: redis://redis:6379
      ALLOWED_HOSTS: '["http://localhost:3000", "http://localhost:3001"]'
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - neo4j
      - redis
    networks:
      - app_network

  # Frontend (for development)
  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  neo4j_data:
  neo4j_logs:
  redis_data:

networks:
  app_network:
    driver: bridge
